[package]
name = "generate_inputs"
version = "0.1.0"
edition = "2024"


[dependencies]
secp256k1 = { version = "0.28", features = ["rand"] }
sha2 = "0.10"
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }