version: '3.8'

services:
  # Midnight Proof Server
  proof-server:
    image: midnight/proof-server:latest
    container_name: ${AGENT_ID:-health-pass-agent}-proof-server
    ports:
      - "${PROOF_SERVER_PORT:-8080}:8080"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - proof-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # ZK Health Pass Midnight MCP Wallet Server
  wallet-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${AGENT_ID:-health-pass-agent}-wallet-server
    ports:
      - "${WALLET_SERVER_PORT:-3000}:3000"
    environment:
      - AGENT_ID=${AGENT_ID:-health-pass-agent}
      - WALLET_SERVER_HOST=0.0.0.0
      - WALLET_SERVER_PORT=3000
      - NETWORK_ID=${NETWORK_ID:-TestNet}
      - WALLET_FILENAME=${WALLET_FILENAME:-midnight-wallet}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - USE_EXTERNAL_PROOF_SERVER=true
      - PROOF_SERVER=http://proof-server:8080
      - INDEXER=${INDEXER:-http://indexer:8080}
      - INDEXER_WS=${INDEXER_WS:-ws://indexer:8080}
      - MN_NODE=${MN_NODE:-http://midnight-node:8080}
      - ZK_HEALTH_PASS_API=${ZK_HEALTH_PASS_API:-http://host.docker.internal:8000}
      - ZK_HEALTH_PASS_CONTRACT=${ZK_HEALTH_PASS_CONTRACT}
      - HEALTH_AUTHORITY_REGISTRY=${HEALTH_AUTHORITY_REGISTRY}
    volumes:
      - wallet-data:/app/storage
      - ./storage/seeds/${AGENT_ID:-health-pass-agent}:/app/storage/seeds/${AGENT_ID:-health-pass-agent}:ro
      - wallet-logs:/app/storage/logs
    depends_on:
      proof-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  proof-data:
    driver: local
  wallet-data:
    driver: local
  wallet-logs:
    driver: local

networks:
  default:
    name: ${AGENT_ID:-health-pass-agent}-network
